delete "fuzzy" tag from this one string, makemessages & compilemessages
This produces a "fatal" error but appears to work regardless:
```bash
CommandError: Execution of msgfmt failed: /Users/paul/Repos/TolaActivity/tola/locale/fr/LC_MESSAGES/django.po:2144: a format specification for argument 'object' doesn't exist in 'msgstr'
msgfmt: found 1 fatal error
```